name: Build-sphinx-docs

on:
  push:
    # branches: [main]

  pull_request:
    # branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install -r docs/requirements-doc.txt

      - name: Build HTML
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: |
          sed -i '/nb_execution_mode = "off"/d' docs/source/conf.py # enable executing jupyter notebook
          cd docs
          make html

      - name: Remove ampersand encoding and token in the generated html
        run: |
          sed -i 's/amp;//g' docs/build/html/Tutorial/Oceans_3.0_API_Tutorial.html
          sed -i 's/token=[a-zA-Z0-9-]\+/token=YOUR_TOKEN/g' docs/build/html/Tutorial/onc_Library_Tutorial.html

      - name: Run ghp-import
        run: |
          ghp-import -npfo docs/build/html
